steps:

- id: "Rodando docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['create', '--name=go-hpa', 'matheussm4224/go-hpa']

- id: "iniciano container docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['start', 'go-hpa']

- id: "test"
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'go-hpa', 'go', 'test']

- id: "deploy k8s"
  name: "gcr.io/cloud-builders/kubectl"
  args:
    - 'apply',
    - '-f',
    - 'k8s/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
