apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  template:
    metadata:
      labels: 
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: matheussm4224/go-hpa
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: "50m"
          limits: 
            cpu: "100m"
